version: '3.8'

services:

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: tonproject-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app_prod.conf:/etc/nginx/conf.d/app.conf
            - ./docker/nginx/ssl:/etc/ssl
        links:
            - app


    #Python Service
    app:
        env_file: .env
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            args:
                - PROJECT_URL=${PROJECT_PROD_URL}
                - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN_PROD}
                - NOWPAYMENTS_API_KEY=${NOWPAYMENTS_API_KEY_PROD}
                - NOWPAYMENTS_SECRET=${NOWPAYMENTS_SECRET_PROD}
                - NOWPAYMENTS_SECRET_2FA=${NOWPAYMENTS_SECRET_2FA_PROD}
                - IS_TESTNET=${IS_TESTNET}
                - TON_API_KEY=${TON_PROD_API_KEY}
                - WALLET=${WALLET_PROD}
                - JETTON_ADDRESS=${JETTON_ADDRESS_PROD}
                - TON_WEBSOCKET_URL=${TON_WEBSOCKET_URL_PROD}
                - MNEMONICS=${MNEMONICS_PROD}
        expose:
            - "8000"
        container_name: tonproject-python
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        links:
            - db

    #MySQL Service
    db:
        image: mysql:8
        container_name: tonproject-mysql
        restart: always
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ton_project
            MYSQL_DATABASE: ton_project
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

    #Redis Service
    redis:
        image: redis:alpine
        container_name: tonproject-redis
        restart: always
        tty: true
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data

#Volumes
volumes:
    dbdata:
        driver: local
    redisdata:
        driver: local
