"""wallet changes

Revision ID: 581e391e6061
Revises: 056f3a99e80f
Create Date: 2024-01-31 16:40:03.944648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581e391e6061'
down_revision: Union[str, None] = '056f3a99e80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('wallet_address_for_user', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'wallet_address_for_user')
    # ### end Alembic commands ###
